initStore([
  {
    id: 0,
    title: 'Guía Completa de Análisis Técnico',
    description: 'Aprende a interpretar gráficos, tendencias y patrones para mejorar tu toma de decisiones en trading.',
    price: 79.99,
    discountPrice: 59.99,
    image: 'img/game-1.jpg',
  },
  {
    id: 1,
    title: 'Manual de Estrategias de Trading Diario',
    description: 'Recopilación de técnicas para operar a corto plazo con estrategias probadas y consejos prácticos.',
    price: 49.99,
    discountPrice: 29.99,
    image: 'img/game-2.jpg',
  },
  {
    id: 2,
    title: 'Curso Avanzado de Gestión de Riesgos',
    description: 'Aprende a gestionar el riesgo de tus operaciones, controlar pérdidas y optimizar ganancias.',
    price: 59.99,
    discountPrice: 44.99,
    image: 'img/game-3.jpg',
  },
  {
    id: 3,
    title: 'Técnicas de Psicología del Trading',
    description: 'Desarrolla disciplina y control emocional para mejorar tus decisiones y resultados en trading.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'img/game-4.jpg',
  },
  {
    id: 4,
    title: 'Estrategias de Scalping y Day Trading',
    description: 'Aprende métodos rápidos y efectivos para aprovechar movimientos de corto plazo en los mercados.',
    price: 79.99,
    discountPrice: 49.99,
    image: 'img/game-5.jpg',
  },
  {
    id: 5,
    title: 'Guía de Planificación y Organización de Operaciones',
    description: 'Organiza tus operaciones, establece objetivos claros y registra tus progresos para mejorar tu rendimiento.',
    price: 69.99,
    discountPrice: 54.99,
    image: 'img/game-6.jpg',
  },
]);
